before:
  hooks:
    - go mod tidy
builds:
  - main: ./cmd/jhol
    ldflags:
      - -X main.version={{.Version}}
    env:
      - CGO_ENABLED=0
checksum:
  name_template: "checksums.txt"
brews:
  - tap:
      owner: winebarrel
      name: homebrew-jhol
    homepage: https://github.com/winebarrel/jhol
    description: CLI to display and check Japanese holidays.
    license: MIT
    install: |
      bin.install 'jhol'
